### PR TITLE
Complete UI restructure: Responsiveness

### PR DESCRIPTION
**Pull request by savioxavier**
Hello there,

This PR makes the UI for the Minima website responsive (sort of)

The following stuff were updated/fixed:
- Update the following components to make them responsive and mobile-friendly:
	- `Hero.vue`
	- `Navbar.vue`
	- `WhatsNew.vue`
	- `[...all].vue` (404 page)
- Update styles for 404 page (`[...all.vue]`)

## Screenshots:

image

image

image

Side note: This is a follow-up of PR #2

### CODE REVIEW

**Comment by savioxavier** [comment]
Should be ready for deployment... except there is one tiny issue:

I couldn't figure out how to toggle the mobile navbar (See `Navbar.vue` of this PR)
**(On line 57 of `Navbar.vue`)**:
```vue
<!-- Mobile menu -->
      <!-- FIX: Toggle element on mobile -->
```
If it's possible to fix it, please do @apoorvcodes. Until then, this PR will be marked as draft

**Comment by savioxavier** [comment]
Or if you would like to fix this in another commit, you can mark this PR as ready for review and merge it to `master`. Your call.

**Comment by apoorvcodes** [comment]
Let's merge it I'll pr later today to fix it

**Comment by apoorvcodes** [comment]
@megatank58 review and merge

**Comment by megatank58** [comment]
oh woops

**Pull request merged**
