### PR TITLE
feat: new docs theme and daisyui

### PR DESCRIPTION
**Pull request by megatank58**
This pull request is not meant for review or merge yet.

Conflicts will not be resolved and this branch will be force pushing to main, any other PRs are halt till this is merged

### CODE REVIEW

**Review by savioxavier — APPROVED** [review]
Looks good to me, might tweak some stuff a bit in later commits.

**Comment by megatank58** [comment]
We will *most probably unless urgent* not be doing any commits to website regarding the core style and core design of the website so if you have any suggestions please drop em here

**Comment by savioxavier** [comment]
> We will most probably unless urgent not be doing any commits to website regarding the core style and core design of the website so if you have any suggestions please drop em here

Since Minima's core color scheme is blue (derived from its logo), we might have to change the green to blue, just to be consistent. We can keep it green, however, but that would require a complete overhaul of Minima's branding.

The font, maybe? It's currently the default font and it doesn't look too good on an Android device.

Improper heading styles? The texts look a bit bold to me. Also, the padding might need a fix, a little bit of breathing space, more like.

Also, there are a few responsiveness issues with different viewport (I tested it out on Responsively App) so that should be taken care of.

~~In addition, the background and color schemes of the code snippets might need to be fixed. The syntax highlighting looks relatively dull compared to the website, plus the code snippet background feels weird in a dark-modded website such as this.~~ (Just refreshed the site now and it's alright)

Other than those, it looks pretty good to me!

**Review by apoorvcodes — CHANGES_REQUESTED** [review]
Change the code block themes to dracula?

**Comment by apoorvcodes** [comment]
@megatank58 eta for the pull

**Comment by megatank58** [comment]
> @megatank58 eta for the pull

when it's ready

**Comment by megatank58** [comment]
Summary of what's left to be done:

- [x] Add "Functions" section to `/docs/main/struct/:struct`
- [x] Add `/docs/main/func/:func` page (based on the previous mentioned section)
- [x] Add theme changer using a drop down in navbar or a button 
- [x] Change the sidebar to use a different unicode

**Comment by megatank58** [comment]
@savioxavier @apoorvcodes review

*Conflicts will not be merged, the branch will be force pushed at once to main*

**Review by apoorvcodes — APPROVED** [review]
Looks great

**Comment by megatank58** [comment]
Force pushed to main! :tada:

**Review by savioxavier — COMMENTED** [review]
Bit late for the review, but looks all good!

**Comment by apoorvcodes** [comment]
@savioxavier lazy, always late for prs

**Comment by savioxavier** [comment]
> @savioxavier lazy, always late for prs

Hey, I got other stuff to do, will try to review future PRs as soon as I can.

**Comment by apoorvcodes** [comment]
> > @savioxavier lazy, always late for prs
> 
> Hey, I got other stuff to do, will try to review future PRs as soon as I can.

It's a joke

**Pull request merged**
